#!/bin/bash

dataDir=${EDDP_API_DATA_DIR:-"./data"}

# Create a new datafile and populate it
mkdir -p "${dataDir}/sqlite"
rm -f "${dataDir}/sqlite/eddp-new.sqlite"
sqlite3 "${dataDir}/sqlite/eddp-new.sqlite" "CREATE TABLE DUMMY(dummy int); DROP TABLE DUMMY;"
./importsystems
./importstations
./importbodies
