package dataDefs

var Governments = map[string]string{
	"government_none":         "None",
	"government_anarchy":      "Anarchy",
	"government_colony":       "Colony",
	"government_communism":    "Communism",
	"government_confederacy":  "Confederacy",
	"government_cooperative":  "Cooperative",
	"government_corporate":    "Corporate",
	"government_democracy":    "Democracy",
	"government_dictatorship": "Dictatorship",
	"government_engineer":     "Engineer",
	"government_feudal":       "Feudal",
	"government_imperial":     "Imperial",
	"government_patronage":    "Patronage",
	"government_prisoncolony": "Prison Colony",
	"government_theocracy":    "Theocracy",
	"government_workshop":     "Workshop",
}

var Volcanisms = map[string]string{
	"ammonia":         "Ammonia",
	"carbon dioxide":  "Carbon Dioxide",
	"metallic":        "Iron",
	"methane":         "Methane",
	"nitrogen":        "Nitrogen",
	"rocky":           "Silicate",
	"silicate vapour": "Silicate vapour",
	"water":           "Water",
}

var States = map[string]string{
	"none":        "None",
	"boom":        "Boom",
	"bust":        "Bust",
	"civilunrest": "Civil Unrest",
	"civilwar":    "Civil War",
	"election":    "Election",
	"expansion":   "Expansion",
	"famine":      "Famine",
	"investment":  "Investment",
	"lockdown":    "Lockdown",
	"outbreak":    "Outbreak",
	"retreat":     "Retreat",
	"war":         "War",
}

var Allegiances = map[string]string{
	"faction_none":        "None",
	"faction_federation":  "Federation",
	"faction_alliance":    "Alliance",
	"faction_empire":      "Empire",
	"faction_independent": "Independent",
	"faction_pirate":      "Pirate",
}

var Economies = map[string]string{
	"economy_none":         "None",
	"economy_agri":         "Agriculture",
	"economy_colony":       "Colony",
	"economy_extraction":   "Extraction",
	"economy_refinery":     "Refinery",
	"economy_industrial":   "Industrial",
	"economy_terraforming": "Terraforming",
	"economy_hightech":     "High Tech",
	"economy_service":      "Service",
	"economy_tourism":      "Tourism",
	"economy_military":     "Military",
}

var Securities = map[string]string{
	"system_security_none":          "None",
	"system_security_low":           "Low",
	"system_security_medium":        "Medium",
	"system_security_high":          "High",
	"system_security_high_anarchy":  "High",
	"galaxy_map_info_state_anarchy": "Anarchy",
	"galaxy_map_info_state_lawless": "Lawless",
}

var Materials = map[string]string{
	"carbon":     "Carbon",
	"iron":       "Iron",
	"nickel":     "Nickel",
	"phosphorus": "Phosphorus",
	"sulphur":    "Sulphur",
	"chromium":   "Chromium",
	"germanium":  "Germanium",
	"manganese":  "Manganese",
	"vanadium":   "Vanadium",
	"zinc":       "Zinc",
	"arsenic":    "Arsenic",
	"niobium":    "Niobium",
	"selenium":   "Selenium",
	"tungsten":   "Tungsten",
	"zirconium":  "Zirconium",
	"cadmium":    "Cadmium",
	"mercury":    "Mercury",
	"molybdenum": "Molybdenum",
	"tin":        "Tin",
	"yttrium":    "Yttrium",
	"antimony":   "Antimony",
	"polonium":   "Polonium",
	"ruthenium":  "Ruthenium",
	"technetium": "Technetium",
	"tellurium":  "Tellurium",
}

var Commodities = map[string]string{
	"agriculturalmedicines":         "Agri-Medicines",
	"animalmeat":                    "Animal Meat",
	"atmosphericextractors":         "Atmospheric Processors",
	"autofabricators":               "Auto-Fabricators",
	"basicnarcotics":                "Narcotics",
	"bioreducinglichen":             "Bioreducing Lichen",
	"bootlegliquor":                 "Legal Drugs",
	"cmmcomposite":                  "CMM Composite",
	"comercialsamples":              "Commercial Samples",
	"coolinghoses":                  "Micro-Weave Cooling Hoses",
	"drones":                        "Limpets",
	"encripteddatastorage":          "Encrypted Data Storage",
	"fruitandvegetables":            "Fruit and Vegetables",
	"hafnium178":                    "Hafnium 178",
	"hazardousenvironmentsuits":     "H.E. Suits",
	"heliostaticfurnaces":           "Microbial Furnaces",
	"hnshockmount":                  "HN Shock Mount",
	"marinesupplies":                "Marine Equipment",
	"metaalloys":                    "Meta-Alloys",
	"mutomimager":                   "Muon Imager",
	"nonlethalweapons":              "Non-lethal Weapons",
	"sap8corecontainer":             "Sap 8 Core Container",
	"skimercomponents":              "Skimmer Components",
	"terrainenrichmentsystems":      "Land Enrichment Systems",
	"trinketsoffortune":             "Trinkets of Hidden Fortune",
	"unkownartifact":                "Unknown Artefact",
	"usscargoancientartefact":       "Ancient Artefact",
	"usscargoexperimentalchemicals": "Experimental Chemicals",
	"usscargomilitaryplans":         "Military Plans",
	"usscargoprototypetech":         "Prototype Tech",
	"usscargorebeltransmissions":    "Rebel Transmissions",
	"usscargotechnicalblueprints":   "Technical Blueprints",
	"usscargotradedata":             "Trade Data",
	"wreckagecomponents":            "Salvageable Wreckage",
}

var CommodityIDs = map[string]int{
	"Explosives":                    1,
	"Hydrogen Fuel":                 2,
	"Mineral Oil":                   3,
	"Pesticides":                    4,
	"Clothing":                      5,
	"Consumer Technology":           6,
	"Domestic Appliances":           7,
	"Beer":                          8,
	"Liquor":                        9,
	"Narcotics":                     10,
	"Tobacco":                       11,
	"Wine":                          12,
	"Algae":                         13,
	"Animal Meat":                   14,
	"Coffee":                        15,
	"Fish":                          16,
	"Food Cartridges":               17,
	"Fruit and Vegetables":          18,
	"Grain":                         19,
	"Synthetic Meat":                20,
	"Tea":                           21,
	"Polymers":                      22,
	"Semiconductors":                23,
	"Superconductors":               24,
	"Atmospheric Processors":        25,
	"Crop Harvesters":               26,
	"Marine Equipment":              27,
	"Microbial Furnaces":            28,
	"Mineral Extractors":            29,
	"Power Generators":              30,
	"Water Purifiers":               31,
	"Agri-Medicines":                32,
	"Basic Medicines":               33,
	"Combat Stabilisers":            34,
	"Performance Enhancers":         35,
	"Progenitor Cells":              36,
	"Aluminium":                     37,
	"Beryllium":                     38,
	"Cobalt":                        39,
	"Copper":                        40,
	"Gallium":                       41,
	"Gold":                          42,
	"Indium":                        43,
	"Lithium":                       44,
	"Palladium":                     45,
	"Platinum":                      46,
	"Silver":                        47,
	"Tantalum":                      48,
	"Titanium":                      49,
	"Uranium":                       50,
	"Bauxite":                       51,
	"Bertrandite":                   52,
	"Coltan":                        53,
	"Gallite":                       54,
	"Indite":                        55,
	"Lepidolite":                    56,
	"Rutile":                        57,
	"Uraninite":                     58,
	"Imperial Slaves":               59,
	"Slaves":                        60,
	"Advanced Catalysers":           61,
	"Animal Monitors":               62,
	"Aquaponic Systems":             63,
	"Auto-Fabricators":              64,
	"Bioreducing Lichen":            65,
	"Computer Components":           66,
	"H.E. Suits":                    67,
	"Land Enrichment Systems":       68,
	"Resonating Separators":         69,
	"Robotics":                      70,
	"Leather":                       72,
	"Natural Fabrics":               73,
	"Synthetic Fabrics":             74,
	"Biowaste":                      75,
	"Chemical Waste":                76,
	"Scrap":                         77,
	"Non-lethal Weapons":            78,
	"Personal Weapons":              79,
	"Reactive Armour":               80,
	"Battle Weapons":                81,
	"Toxic Waste":                   82,
	"Painite":                       83,
	"Limpet":                        84,
	"Eranin Pearl Whiskey":          85,
	"Kamorin Historic Weapons":      86,
	"Lucan Onion Head":              87,
	"Motrona Experience Jelly":      88,
	"Onion Head":                    89,
	"Rusani Old Smokey":             90,
	"Tarach Spice":                  91,
	"Terra Mater Blood Bores":       92,
	"Wolf Fesh":                     93,
	"Wuthielo Ku Froth":             94,
	"Ai Relics":                     95,
	"Antiquities":                   96,
	"Osmium":                        97,
	"Sap 8 Core Container":          98,
	"Trinkets Of Hidden Fortune":    99,
	"Trade Data":                    100,
	"Thermal Cooling Units":         101,
	"Skimmer Components":            102,
	"Geological Equipment":          103,
	"Structural Regulators":         104,
	"Pyrophyllite":                  105,
	"Moissanite":                    106,
	"Goslarite":                     107,
	"Cryolite":                      108,
	"Thorium":                       109,
	"Thallium":                      110,
	"Lanthanum":                     111,
	"Bismuth":                       112,
	"Bootleg Liquor":                113,
	"Meta-Alloys":                   114,
	"Ceramic Composites":            115,
	"Evacuation Shelter":            116,
	"Synthetic Reagents":            117,
	"Surface Stabilisers":           118,
	"Building Fabricators":          119,
	"Landmines":                     121,
	"Nerve Agents":                  122,
	"Occupied CryoPod":              123,
	"Muon Imager":                   124,
	"Lavian Brandy":                 125,
	"Black Box":                     126,
	"Military Plans":                127,
	"Ancient Artefact":              128,
	"Rare Artwork":                  129,
	"Experimental Chemicals":        130,
	"Rebel Transmissions":           131,
	"Prototype Tech":                132,
	"Technical Blueprints":          133,
	"HIP 10175 Bush Meat":           134,
	"Albino Quechua Mammoth":        135,
	"Utgaroar Millennial Eggs":      136,
	"Witchhaul Kobe Beef":           137,
	"Karsuki Locusts":               138,
	"Giant Irukama Snails":          139,
	"Baltah Sine Vacuum Krill":      140,
	"Ceti Rabbits":                  141,
	"Kachirigin Filter Leeches":     142,
	"Lyrae Weed":                    143,
	"Borasetani Pathogenetics":      144,
	"HIP 118311 Swarm":              145,
	"Kongga Ale":                    146,
	"Alacarakmo Skin Art":           147,
	"Eleu Thermals":                 148,
	"Eshu Umbrellas":                149,
	"Karetii Couture":               150,
	"Njangari Saddles":              151,
	"Any Na Coffee":                 152,
	"CD-75 Kitten Brand Coffee":     153,
	"Goman Yaupon Coffee":           154,
	"Volkhab Bee Drones":            155,
	"Kinago Violins":                156,
	"Nguna Modern Antiques":         157,
	"Rajukru Multi-Stoves":          158,
	"Tiolce Waste2Paste Units":      159,
	"Chi Eridani Marine Paste":      160,
	"Esuseku Caviar":                161,
	"Live Hecate Sea Worms":         162,
	"Helvetitj Pearls":              163,
	"HIP Proto-Squid":               164,
	"Coquim Spongiform Victuals":    165,
	"Eden Apples Of Aerial":         166,
	"Neritus Berries":               167,
	"Ochoeng Chillies":              168,
	"Deuringas Truffles":            169,
	"HR 7221 Wheat":                 170,
	"Jaroua Rice":                   171,
	"Belalans Ray Leather":          172,
	"Damna Carapaces":               173,
	"Rapa Bao Snake Skins":          174,
	"Vanayequi Ceratomorpha Fur":    175,
	"Bast Snake Gin":                176,
	"Thrutis Cream":                 177,
	"Wulpa Hyperbore Systems":       178,
	"Aganippe Rush":                 179,
	"Holva Duelling Blades":         180,
	"Gilya Signature Weapons":       181,
	"Delta Phoenicis Palms":         182,
	"Toxandji Virocide":             183,
	"Xihe Biomorphic Companions":    184,
	"Sanuma Decorative Meat":        185,
	"Ethgreze Tea Buds":             186,
	"Ceremonial Heike Tea":          187,
	"Tanmark Tranquil Tea":          188,
	"Az Cancri Formula 42":          189,
	"Kamitra Cigars":                190,
	"Yaso Kondi Leaf":               191,
	"Chateau De Aegaeon":            192,
	"Waters Of Shintara":            193,
	"Ophiuch Exino Artefacts":       194,
	"Aepyornis Egg":                 195,
	"Saxon Wine":                    196,
	"Centauri Mega Gin":             197,
	"Anduliga Fire Works":           198,
	"Banki Amphibious Leather":      199,
	"Cherbones Blood Crystals":      200,
	"Geawen Dance Dust":             201,
	"Gerasian Gueuze Beer":          202,
	"Haidne Black Brew":             203,
	"Havasupai Dream Catcher":       204,
	"Burnham Bile Distillate":       205,
	"HIP Organophosphates":          206,
	"Jaradharre Puzzle Box":         207,
	"Koro Kung Pellets":             208,
	"Void Extract Coffee":           209,
	"Honesty Pills":                 210,
	"Non Euclidian Exotanks":        211,
	"LTT Hypersweet":                212,
	"Mechucos High Tea":             213,
	"Medb Starlube":                 214,
	"Mokojing Beast Feast":          215,
	"Mukusubii Chitin-Os":           216,
	"Mulachi Giant Fungus":          217,
	"Ngadandari Fire Opals":         218,
	"Tiegfries Synth Silk":          219,
	"Uzumoku Low-G Wings":           220,
	"V Herculis Body Rub":           221,
	"Wheemete Wheat Cakes":          222,
	"Vega Slimweed":                 223,
	"Altairian Skin":                224,
	"Pavonis Ear Grubs":             225,
	"Jotun Mookah":                  226,
	"Giant Verrix":                  227,
	"Indi Bourbon":                  228,
	"Arouca Conventual Sweets":      229,
	"Tauri Chimes":                  230,
	"Zeessze Ant Grub Glue":         231,
	"Pantaa Prayer Sticks":          232,
	"Fujin Tea":                     233,
	"Chameleon Cloth":               234,
	"Orrerian Vicious Brew":         235,
	"Uszaian Tree Grub":             236,
	"Momus Bog Spaniel":             237,
	"Diso Ma Corn":                  238,
	"Leestian Evil Juice":           239,
	"Azure Milk":                    240,
	"Leathery Eggs":                 241,
	"Alya Body Soap":                242,
	"Vidavantian Lace":              243,
	"Jaques Quinentian Still":       244,
	"Soontill Relics":               245,
	"Unknown Artefact":              246,
	"Hafnium 178":                   247,
	"Military Intelligence":         248,
	"The Hutton Mug":                249,
	"Sothis Crystalline Gold":       250,
	"Salvageable Wreckage":          251,
	"Encrypted Data Storage":        252,
	"Personal Effects":              253,
	"Commercial Samples":            254,
	"Tactical Data":                 255,
	"Assault Plans":                 256,
	"Encrypted Correspondence":      257,
	"Diplomatic Bag":                258,
	"Scientific Research":           259,
	"Scientific Samples":            260,
	"Political Prisoner":            261,
	"Hostage":                       262,
	"Geological Samples":            263,
	"Master Chefs":                  264,
	"Crystalline Spheres":           265,
	"Taaffeite":                     266,
	"Jadeite":                       267,
	"Unstable Data Core":            268,
	"Onionhead Alpha Strain":        269,
	"Occupied Escape Pod":           270,
	"Water":                         271,
	"Onionhead Beta Strain":         272,
	"Praseodymium":                  273,
	"Bromellite":                    274,
	"Samarium":                      275,
	"Low Temperature Diamonds":      276,
	"Hydrogen Peroxide":             277,
	"Liquid Oxygen":                 278,
	"Methanol Monohydrate":          279,
	"Lithium Hydroxide":             280,
	"Methane Clathrate":             281,
	"Insulating Membrane":           282,
	"CMM Composite":                 283,
	"Micro-Weave Cooling Hoses":     284,
	"Neofabric Insulation":          285,
	"Articulation Motors":           286,
	"HN Shock Mount":                287,
	"Emergency Power Cells":         288,
	"Power Converter":               289,
	"Energy Grid Assembly":          290,
	"Power Transfer Bus":            291,
	"Radiation Baffle":              292,
	"Exhaust Manifold":              293,
	"Reinforced Mounting Plate":     294,
	"Heatsink Interlink":            295,
	"Magnetic Emitter Coil":         296,
	"Modular Terminals":             297,
	"Nanobreakers":                  298,
	"Telemetry Suite":               299,
	"Micro Controllers":             300,
	"Ion Distributor":               301,
	"Hardware Diagnostic Sensor":    302,
	"Conductive Fabrics":            303,
	"Military Grade Fabrics":        304,
	"Advanced Medicines":            305,
	"Medical Diagnostic Equipment":  306,
	"Survival Equipment":            307,
	"Data Core":                     308,
	"Galactic Travel Guide":         309,
	"Mysterious Idol":               310,
	"Prohibited Research Materials": 311,
	"Antimatter Containment Unit":   312,
	"Space Pioneer Relics":          313,
	"Fossil Remnants":               314,
	"Unknown Probe":                 315,
	"Precious Gems":                 316,
}
